[tool.poetry]
name = "zamilovich"
version = "0.1.0"
description = "matroskin bot"
authors = ["4i4ikov <4i4ikov@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

